baseurl = "https://blog.fercontreras.com"
title = "Fernando Contreras"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

publishDir = "fercreek.github.io"
disqusShortname = "fercreek"

[params]
    author = "Fernando Contreras"
    info = "SOFTWARE ENGINEER, TRADER, DANCER AND WRITER BY HOBBY"
    description = "Fernando Contreras's personal website"
    keywords = "blog,developer,personal,engineer,ruby,rails,python,django,javascript"
    avatarurl = "images/me.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook"
    weight = 1
    url = "https://www.facebook.com/fercreek/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/fercreek/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/fercreek7/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/fercreek/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://blog.fercontreras.com"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "https://blog.fercontreras.com"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "My Impossible List"
    weight = 3
    url = "/my-impossible-list/"
[[menu.main]]
    name = "What I'm Doing Now"
    weight = 4
    url = "/now/"
[[menu.main]]
    name = "Projects"
    weight = 5
    url = "/projects/"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.93.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.93.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.93.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.93.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200